# 1. Используем официальный образ Ubuntu
FROM ubuntu:22.04

# 2. Устанавливаем зависимости для сборки Drogon и C++
RUN apt-get update && apt-get install -y \
    g++ \
    cmake \
    git \
    make \
    libjsoncpp-dev \
    uuid-dev \
    openssl \
    zlib1g-dev \
    libssl-dev \
    libsqlite3-dev \
    libmariadb-dev \
    libmariadb-dev-compat \
    postgresql-all \
    && rm -rf /var/lib/apt/lists/*

# 3. Создаем рабочую директорию внутри контейнера
WORKDIR /app

# 4. Копируем проект внутрь контейнера
COPY . .

# 5. Создаем папку для сборки
RUN mkdir build

# 6. Собираем проект
RUN cd build && cmake .. && make

# 7. Указываем порт, на котором работает Drogon
EXPOSE 8080

# 8. Запускаем приложение
CMD ["./build/my-drogon-app"]